[project]
name = "quiz-demo"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.140.0",
    "pydantic>=2.13.4",
    "python-multipart>=0.0.32",
    "sphinx>=9.1.0",
    "sphinx-autobuild>=2025.8.25",
    "sphinx-conestack-theme>=1.1.1",
    "sphinx-markdown-builder>=0.6.10",
    "sphinx-new-tab-link>=0.8.1",
]
